version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - MONGDO_URI=mongodb://mongodb:27017
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: